#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#customer:
#  type: rest
#  resource: App\Controller\CustomerController
#  prefix: /v1
#  name_prefix: v1_
#  defaults: {_format: json}

#default:
#  type: rest
#  resource: App\Controller\DefaultController
#  prefix: /v1
#  name_prefix: v1_
#  defaults: {_format: json}
api_login_check:
  path: /auth/login_check
